# Generated by Django 5.2.1 on 2025-06-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Серийный номер')),
                ('category', models.CharField(choices=[('electronics', 'Электроника'), ('tool', 'Инструмент'), ('safety', 'Безопасность'), ('communication', 'Связь'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('installed_date', models.DateField(verbose_name='Дата установки')),
                ('seal_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время пломбирования')),
                ('seal_responsible', models.CharField(blank=True, max_length=100, verbose_name='Ответственный за пломбирование')),
                ('unseal_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время снятия пломбы')),
                ('unseal_reason', models.CharField(blank=True, max_length=200, verbose_name='Причина снятия пломбы')),
                ('unseal_responsible', models.CharField(blank=True, max_length=100, verbose_name='Ответственный за снятие пломбы')),
                ('unscheduled_seal_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата внепланового пломбирования')),
                ('unscheduled_seal_reason', models.CharField(blank=True, max_length=200, verbose_name='Причина внепланового пломбирования')),
                ('maintenance_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата технического обслуживания')),
                ('maintenance_reason', models.CharField(blank=True, max_length=200, verbose_name='Причина технического обслуживания')),
                ('repair_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата ремонта')),
                ('repair_reason', models.CharField(blank=True, max_length=200, verbose_name='Причина ремонта')),
                ('is_operable', models.CharField(choices=[('operable', 'Исправно'), ('in_repair', 'В ремонте'), ('faulty', 'Неисправно'), ('on_maintenance', 'На ТО'), ('unknown', 'Не определено')], default='operable', max_length=20, verbose_name='Исправность')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'permissions': [('can_assign_responsible', 'Может назначать ответственных сотрудников'), ('can_set_unplanned_seal', 'Может устанавливать внеплановое пломбирование'), ('can_set_maintenance_date', 'Может устанавливать дату ТО'), ('can_set_repair_date', 'Может устанавливать дату ремонта')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('car', 'Легковой автомобиль'), ('truck', 'Грузовик'), ('bus', 'Автобус'), ('special', 'Спецтехника'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Гос. номер')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Производитель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('vin', models.CharField(blank=True, max_length=50, verbose_name='VIN')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Цвет')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('maintenance_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата технического обслуживания')),
                ('repair_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата ремонта')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'permissions': [('can_assign_responsible', 'Может назначать ответственных сотрудников'), ('can_set_unplanned_seal', 'Может устанавливать внеплановое пломбирование'), ('can_set_maintenance_date', 'Может устанавливать дату ТО'), ('can_set_repair_date', 'Может устанавливать дату ремонта')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Операция')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.CharField(blank=True, max_length=100, verbose_name='Пользователь')),
                ('details', models.TextField(blank=True, verbose_name='Детали изменений')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='TS_equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Журнал оборудования',
                'verbose_name_plural': 'Журналы оборудования',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RepairHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('maintenance', 'ТО'), ('repair', 'Ремонт')], max_length=20, verbose_name='Тип работ')),
                ('date', models.DateField(verbose_name='Дата работ')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег/наработка')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('responsible', models.CharField(max_length=100, verbose_name='Ответственный')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В работе'), ('done', 'Выполнено'), ('cancelled', 'Отменено'), ('postponed', 'Отложено')], default='done', max_length=20, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to='repair_docs/', verbose_name='Документ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_history', to='TS_equipment.equipment', verbose_name='Оборудование')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_history', to='TS_equipment.vehicle', verbose_name='ТС')),
            ],
            options={
                'verbose_name': 'История ремонта',
                'verbose_name_plural': 'История ремонтов',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('maintenance', 'ТО'), ('repair', 'Ремонт')], max_length=20, verbose_name='Тип работ')),
                ('date', models.DateField(verbose_name='Дата работ')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег/наработка')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('responsible', models.CharField(max_length=100, verbose_name='Ответственный')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В работе'), ('done', 'Выполнено'), ('cancelled', 'Отменено'), ('postponed', 'Отложено')], default='planned', max_length=20, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to='maintenance_docs/', verbose_name='Документ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='TS_equipment.equipment', verbose_name='Оборудование')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='TS_equipment.vehicle', verbose_name='ТС')),
            ],
            options={
                'verbose_name': 'Запись ТОиР',
                'verbose_name_plural': 'ТОиР',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='installed_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='TS_equipment.vehicle', verbose_name='Транспортное средство'),
        ),
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Операция')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.CharField(blank=True, max_length=100, verbose_name='Пользователь')),
                ('details', models.TextField(blank=True, verbose_name='Детали изменений')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='TS_equipment.vehicle', verbose_name='ТС')),
            ],
            options={
                'verbose_name': 'Журнал транспорта',
                'verbose_name_plural': 'Журналы транспорта',
                'ordering': ['-timestamp'],
            },
        ),
    ]
